name: Generate PDF from Markdown

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: List files in directory
      run: ls -l

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: pandoc path/to/your/fluoxetine.md -o path/to/your/fluoxetine.pdf
      
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: fluoxetine-pdf
        path: path/to/your/fluoxetine.pdf
